In [12]:
import requests
from bs4 import BeautifulSoup
import time
import smtplib
import csv
import pandas as pd

In [13]:
productlinks=[]
whiskylist=[]
for x in range(1,2):
    url=('https://www.thewhiskyexchange.com/c/35/japanese-whisky')
    headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102"}
    baseurl=('https://www.thewhiskyexchange.com/')
    page=requests.get(url)
    soup=BeautifulSoup(page.content,'lxml')
    soup2=BeautifulSoup(soup.prettify(),'lxml')
    product= soup2.find_all('li', class_="product-grid__item")
    for item in product:
        for link in item.find_all('a',href=True):
            productlinks.append(baseurl +link['href'])
            
print(productlinks)

['https://www.thewhiskyexchange.com//p/2940/yamazaki-12-year-old', 'https://www.thewhiskyexchange.com//p/23928/nikka-coffey-grain-whisky', 'https://www.thewhiskyexchange.com//p/23771/hakushu-distillers-reserve', 'https://www.thewhiskyexchange.com//p/37317/the-chita-whisky', 'https://www.thewhiskyexchange.com//p/36362/suntory-toki', 'https://www.thewhiskyexchange.com//p/32761/yoichi-single-malt', 'https://www.thewhiskyexchange.com//p/32762/miyagikyo-single-malt', 'https://www.thewhiskyexchange.com//p/45367/kaiyo-mizunara-oak-cask-strength', 'https://www.thewhiskyexchange.com//p/34461/akashi-5-year-old-sherry-cask-half-litre', 'https://www.thewhiskyexchange.com//p/52590/kaiyo-peated-mizunara-oak', 'https://www.thewhiskyexchange.com//p/37325/suntory-torys-classic', 'https://www.thewhiskyexchange.com//p/2944/yoichi-10-year-old', 'https://www.thewhiskyexchange.com//p/2926/miyagikyo-15-year-old', 'https://www.thewhiskyexchange.com//p/2925/miyagikyo-12-year-old', 'https://www.thewhiskyexchange.com//p/2924/miyagikyo-10-year-old', 'https://www.thewhiskyexchange.com//p/64652/nikka-coffey-grain-whisky-show-package-2-sunday-tickets', 'https://www.thewhiskyexchange.com//p/64651/nikka-coffey-grain-whisky-show-package-1-sunday-ticket', 'https://www.thewhiskyexchange.com//p/63405/the-house-of-suntory-triology-pack-3x20cl', 'https://www.thewhiskyexchange.com//p/57939/chichibu-2009-10-year-old-artist-international-10th-anniversary', 'https://www.thewhiskyexchange.com//p/55785/ichiros-malt-grain-japanese-blended-whisky-2020', 'https://www.thewhiskyexchange.com//p/45906/chichibu-2010-cask-1000', 'https://www.thewhiskyexchange.com//p/25880/hanyu-1985-the-joker-monochrome-label', 'https://www.thewhiskyexchange.com//p/21444/karuizawa-1981-sherry-cask-6056', 'https://www.thewhiskyexchange.com//p/10132/hakushu-10-year-old']

In [14]:
for link in productlinks:
    print(link)

https://www.thewhiskyexchange.com//p/2940/yamazaki-12-year-old
https://www.thewhiskyexchange.com//p/23928/nikka-coffey-grain-whisky
https://www.thewhiskyexchange.com//p/23771/hakushu-distillers-reserve
https://www.thewhiskyexchange.com//p/37317/the-chita-whisky
https://www.thewhiskyexchange.com//p/36362/suntory-toki
https://www.thewhiskyexchange.com//p/32761/yoichi-single-malt
https://www.thewhiskyexchange.com//p/32762/miyagikyo-single-malt
https://www.thewhiskyexchange.com//p/45367/kaiyo-mizunara-oak-cask-strength
https://www.thewhiskyexchange.com//p/34461/akashi-5-year-old-sherry-cask-half-litre
https://www.thewhiskyexchange.com//p/52590/kaiyo-peated-mizunara-oak
https://www.thewhiskyexchange.com//p/37325/suntory-torys-classic
https://www.thewhiskyexchange.com//p/2944/yoichi-10-year-old
https://www.thewhiskyexchange.com//p/2926/miyagikyo-15-year-old
https://www.thewhiskyexchange.com//p/2925/miyagikyo-12-year-old
https://www.thewhiskyexchange.com//p/2924/miyagikyo-10-year-old
https://www.thewhiskyexchange.com//p/64652/nikka-coffey-grain-whisky-show-package-2-sunday-tickets
https://www.thewhiskyexchange.com//p/64651/nikka-coffey-grain-whisky-show-package-1-sunday-ticket
https://www.thewhiskyexchange.com//p/63405/the-house-of-suntory-triology-pack-3x20cl
https://www.thewhiskyexchange.com//p/57939/chichibu-2009-10-year-old-artist-international-10th-anniversary
https://www.thewhiskyexchange.com//p/55785/ichiros-malt-grain-japanese-blended-whisky-2020
https://www.thewhiskyexchange.com//p/45906/chichibu-2010-cask-1000
https://www.thewhiskyexchange.com//p/25880/hanyu-1985-the-joker-monochrome-label
https://www.thewhiskyexchange.com//p/21444/karuizawa-1981-sherry-cask-6056
https://www.thewhiskyexchange.com//p/10132/hakushu-10-year-old

In [15]:
 for link in productlinks:
        r=requests.get(link,headers=headers)
        soup2=BeautifulSoup(r.content,'lxml')
        
        try:
            rating=soup2.find('div',class_='review-overview').text.strip()
            name=soup2.find('h1',class_='product-main__name').text.strip()
            price=soup2.find('p',class_='product-action__price').text.strip()[1:]
        except:
            rating='no rating'
            name='no name'
            price='no price'
           
            
       
        whisky={'name':name,'price':price,'rating':rating,}
        whiskylist.append(whisky)
        
        print(whisky)
        


#soup4=BeautifulSoup(soup3.prettify(),'lxml')

{'name': 'Yamazaki 12 Year Old', 'price': '135', 'rating': '4.5\n\n\n(92\xa0Reviews)'}
{'name': 'Nikka Coffey Grain Whisky', 'price': '56.95', 'rating': '4.5\n\n\n(51\xa0Reviews)'}
{'name': "Hakushu Distiller's Reserve", 'price': '66.95', 'rating': '4.5\n\n\n(28\xa0Reviews)'}
{'name': 'The Chita Whisky', 'price': '49.95', 'rating': '4.5\n\n\n(40\xa0Reviews)'}
{'name': 'Suntory Toki', 'price': '31.95', 'rating': '4\n\n\n(33\xa0Reviews)'}
{'name': 'Yoichi Single Malt', 'price': '75.95', 'rating': '4.5\n\n\n(9\xa0Reviews)'}
{'name': 'Miyagikyo Single Malt', 'price': '75.95', 'rating': '4.5\n\n\n(9\xa0Reviews)'}
{'name': 'Kaiyo Mizunara Oak Cask Strength', 'price': '110', 'rating': '5\n\n\n(3\xa0Reviews)'}
{'name': 'Akashi 5 Year Old\nSherry Cask Half Litre', 'price': '150', 'rating': '5\n\n\n(2\xa0Reviews)'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'Suntory Torys Classic', 'price': '30.45', 'rating': '3.5\n\n\n(2\xa0Reviews)'}
{'name': 'Yoichi 10 Year Old', 'price': '500', 'rating': '4.5\n\n\n(9\xa0Reviews)'}
{'name': 'Miyagikyo 15 Year Old', 'price': '1,000', 'rating': '4\n\n\n(1\xa0Review)'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'no name', 'price': 'no price', 'rating': 'no rating'}
{'name': 'Hakushu 10 Year Old', 'price': '375', 'rating': '5\n\n\n(1\xa0Review)'}

In [19]:

import pandas as pd
df=pd.DataFrame(whiskylist)
df

                                         name     price                 rating
0                        Yamazaki 12 Year Old       135  4.5\n\n\n(92Â Reviews)
1                   Nikka Coffey Grain Whisky     56.95  4.5\n\n\n(51Â Reviews)
2                 Hakushu Distiller's Reserve     66.95  4.5\n\n\n(28Â Reviews)
3                            The Chita Whisky     49.95  4.5\n\n\n(40Â Reviews)
4                                Suntory Toki     31.95    4\n\n\n(33Â Reviews)
5                          Yoichi Single Malt     75.95   4.5\n\n\n(9Â Reviews)
6                       Miyagikyo Single Malt     75.95   4.5\n\n\n(9Â Reviews)
7            Kaiyo Mizunara Oak Cask Strength       110     5\n\n\n(3Â Reviews)
8   Akashi 5 Year Old\nSherry Cask Half Litre       150     5\n\n\n(2Â Reviews)
9                                     no name  no price              no rating
10                      Suntory Torys Classic     30.45   3.5\n\n\n(2Â Reviews)
11                         Yoichi 10 Year Old       500   4.5\n\n\n(9Â Reviews)
12                      Miyagikyo 15 Year Old     1,000      4\n\n\n(1Â Review)
13                                    no name  no price              no rating
14                                    no name  no price              no rating
15                                    no name  no price              no rating
16                                    no name  no price              no rating
17                                    no name  no price              no rating
18                                    no name  no price              no rating
19                                    no name  no price              no rating
20                                    no name  no price              no rating
21                                    no name  no price              no rating
22                                    no name  no price              no rating
23                        Hakushu 10 Year Old       375      5\n\n\n(1Â Review)

In [27]:
df.to_csv('japanesewhiskylist.csv',index=False)

In [28]:
pd.read_csv('japanesewhiskylist.csv')

                                         name     price                 rating
0                        Yamazaki 12 Year Old       135  4.5\n\n\n(92Â Reviews)
1                   Nikka Coffey Grain Whisky     56.95  4.5\n\n\n(51Â Reviews)
2                 Hakushu Distiller's Reserve     66.95  4.5\n\n\n(28Â Reviews)
3                            The Chita Whisky     49.95  4.5\n\n\n(40Â Reviews)
4                                Suntory Toki     31.95    4\n\n\n(33Â Reviews)
5                          Yoichi Single Malt     75.95   4.5\n\n\n(9Â Reviews)
6                       Miyagikyo Single Malt     75.95   4.5\n\n\n(9Â Reviews)
7            Kaiyo Mizunara Oak Cask Strength       110     5\n\n\n(3Â Reviews)
8   Akashi 5 Year Old\nSherry Cask Half Litre       150     5\n\n\n(2Â Reviews)
9                                     no name  no price              no rating
10                      Suntory Torys Classic     30.45   3.5\n\n\n(2Â Reviews)
11                         Yoichi 10 Year Old       500   4.5\n\n\n(9Â Reviews)
12                      Miyagikyo 15 Year Old     1,000      4\n\n\n(1Â Review)
13                                    no name  no price              no rating
14                                    no name  no price              no rating
15                                    no name  no price              no rating
16                                    no name  no price              no rating
17                                    no name  no price              no rating
18                                    no name  no price              no rating
19                                    no name  no price              no rating
20                                    no name  no price              no rating
21                                    no name  no price              no rating
22                                    no name  no price              no rating
23                        Hakushu 10 Year Old       375      5\n\n\n(1Â Review)